networks:
  backend:
    driver: ${NETWORKS_DRIVER}

include:
  - path: postgres/compose.yaml
    project_directory: .
    env_file: postgres/defaults.env
  - path: rabbitmq/compose.yaml
    project_directory: .
    env_file: rabbitmq/defaults.env
  - path: smocker/compose.yaml
    project_directory: .
    env_file: smocker/defaults.env
  - path: ngrok/compose.yaml
    project_directory: .
    env_file: ngrok/defaults.env
  - path: 9router/compose.yaml
    project_directory: .
    env_file: 9router/defaults.env
  - path: hermes/compose.yaml
    project_directory: .
    env_file: hermes/defaults.env
